# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3210855ed96f7b7696e070ee94b63e1758ed241fdc0ab5ef814a40ddffad1a5d371f02de7ef5ec8a2be7f1a208bf99d1751230d5391ff630fce6cbd1e9bc4732

test:
  secret_key_base: 3d39afa265b2417af5763c33bca52456e343169164489c31de22eac2ad943a28fc09de65017a5ca449d9d03a1e7b2c00776576034fb1dc95ac9d7e217e649c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
